# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40700e9160fd99e69ea0814f0c5cb0f521abe359a76b30bced7e71a33d384f34abc06d887cfdd358d31a7a1c6bdd94807c721a2826eb8a8df2c61a12ddec211f

test:
  secret_key_base: 0082b12a6000db01f26461ef1ab2802cec31c8b8d301978639bf033f3a18328bed2e5a9b6ede03c1ae512391106a716e976b28a6b3d0a1c733a231d5cea7715d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
